services:
  mariadb:
    build:
      context: ./MariaDB
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    build:
      context: ./Wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception-network
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    restart: always

  nginx:
    build:
      context: ./Nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception-network
    depends_on:
      - wordpress
    extra_hosts:
    - "derjavec.42.fr:127.0.0.1"
    ports:
      - "443:443"
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/derjavec/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/derjavec/data/wordpress

networks:
  inception-network:
    driver: bridge


